service: slack-echo-bot

provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, 'dev'}
  region: "ap-northeast-1"
  environment:
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}

functions:
  slack_bot:
    handler: app.handler
    events:
      - http:
          path: slack/events
          method: post

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux